name: admin_app_website
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  #cupertino_icons: ^0.1.3
  http: ^0.13.3
  image_picker: ^0.8.4
  #provider: ^6.1.6
  #table_sticky_headers: ^0.2.4
  #cached_network_image: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  #flutter_web_scraper: ^0.3.0
  #flutter_launcher_name: ^0.0.1
  #for web support
  build_runner: ^2.1.4
  build_web_compilers: ^3.0.0

flutter:
  uses-material-design: true
